version: 2.1

orbs:
  browser-tools: circleci/browser-tools@1.1.0

jobs:
  build:
    docker:
      - image: cimg/openjdk:17.0
    steps:
      - browser-tools/install-chrome
      - checkout
      - run:
          command: mvn clean test

workflows:
  build-and-test:
    jobs:
      - build